### ISSUE TITLE
En vista gráfica de productos

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#10]
Iniciar la pantalla con un rango de tiempo de 7 días (Es decir la última semana).

![imagen](https://user-images.githubusercontent.com/1143320/107661202-0f533d00-6c57-11eb-8990-85c19e2805a8.png)

**Comment by kellypaulinc** [comment]
![solución2](https://user-images.githubusercontent.com/78521567/107717005-a1336800-6ca0-11eb-8f95-43f9a982f43c.PNG)
