### ISSUE TITLE
Dato mayor no muestra el valor

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#11]
Obtener el valor mayor de los datos y establecer la escala + una holgura. Esto permitiría visualizar el valor.

![Peek 11-02-2021 10-54](https://user-images.githubusercontent.com/1143320/107661816-a28c7280-6c57-11eb-8457-15fc4148c7ee.gif)

**Comment by kellypaulinc** [comment]
https://user-images.githubusercontent.com/78521567/107717290-45b5aa00-6ca1-11eb-8581-d478cb5aa3c1.mp4
