### ISSUE TITLE
Agregar rango de fechas en título de gráfico.

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#12]
Se debe indicar el rango de fechas de los datos mostrados en el gráfico.

![imagen](https://user-images.githubusercontent.com/1143320/107662064-e67f7780-6c57-11eb-8569-9db0f7d7875d.png)

**Comment by kellypaulinc** [comment]
![solucion4](https://user-images.githubusercontent.com/78521567/107717395-801f4700-6ca1-11eb-9e03-60e2bc0b9f0d.PNG)
