### ISSUE TITLE
Usar variable de configuración del sistema para factor de escala de gráficos

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#15]
En sentencias del tipo:  

_double scale = (double) product.getData().values().toArray()[0]*1.5; //Aumentar un poco más la escala_

se debe usar variables de configuración del sistema desde settingHome

**Comment by jlgranda** [comment]
Adicionalmente en esa línea controlar que el [0] exista realmente, sino puede lanzar una excepción de elemento no encontrado.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.jlgranda.fede.controller.sales.SummaryHome.createBarModelAmount(SummaryHome.java:337)

**Comment by kellypaulinc** [comment]
Uso de settingHome y verificación de elemento
if (!product.getData().isEmpty()) {
            scale = (double) product.getData().values().toArray()[0] * Double.valueOf(settingHome.getValue("app.fede.barchart.sales.multiply.scale", "1.2"));
            yAxis.setMax(scale);
        }
