### ISSUE TITLE
Al guardar (actualizar) invoice no almacena el campo #Factura

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#18]
Path: /appsventas-web/pages/fede/sales/invoice.jsf
![imagen](https://user-images.githubusercontent.com/1143320/107853899-70f5e180-6de6-11eb-8344-b181d54a3378.png)

**Comment by jlgranda** [comment]
IMPORTANTE! Actualizar rama desde master.

**Comment by kellypaulinc** [comment]
https://user-images.githubusercontent.com/78521567/108517715-c2461b00-7295-11eb-965b-bdd11851f5ef.mp4

**Comment by jlgranda** [comment]
Genial.
