### ISSUE TITLE
Mo permite guardar números decimales

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#19]
![imagen](https://user-images.githubusercontent.com/1143320/107857131-8543d980-6dfa-11eb-89f4-33dde562d0e0.png)

**Comment by jlgranda** [comment]
Al agregar nuevos registros, la pantalla inicia con valor 1 y el valor del iva a 0.12. Debe iniciar vacio.
![imagen](https://user-images.githubusercontent.com/1143320/107866228-7bdb6100-6e3c-11eb-8725-bd97fbf63b98.png)

**Comment by kellypaulinc** [comment]
https://user-images.githubusercontent.com/78521567/108424196-de4eab80-7206-11eb-9e87-7f174e5227c2.mp4

**Comment by jlgranda** [comment]
Sólo un detalle, el mensaje de validación de total (subtotal + IVA), que mejor sea marcado como Error.

**Comment by kellypaulinc** [comment]
https://user-images.githubusercontent.com/78521567/108427194-cd079e00-720a-11eb-901a-e5b6bbbb29aa.mp4
