### ISSUE TITLE
Agregar valor de IVA y TOTAL como ayuda para el cajero

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#21]
![imagen](https://user-images.githubusercontent.com/1143320/107866416-a1696a00-6e3e-11eb-8bc0-e0a52615b720.png)

**Comment by kellypaulinc** [comment]
Calculo automático del IVA y el total de pago + impuestos
![solucion#21](https://user-images.githubusercontent.com/78521567/107989423-4780b580-6fa0-11eb-88a7-8d6031773244.PNG)

**Comment by kellypaulinc** [comment]
Existe una interrogante... El valor de IVA y Monto recibido en el input no se modifica a pesar del uso del listener update.
![solucion#21](https://user-images.githubusercontent.com/78521567/108003663-73606300-6fc1-11eb-8b04-c301a558388b.PNG)

**Comment by kellypaulinc** [comment]
![solucion#21](https://user-images.githubusercontent.com/78521567/108084477-3a1c0780-7042-11eb-9a7c-2d08b1f9fd14.PNG)

**Comment by jlgranda** [comment]
![DIBUJITO](https://user-images.githubusercontent.com/1143320/108105037-149af800-705a-11eb-9e9c-c6203685da6f.png)

**Comment by kellypaulinc** [comment]
![solucion#21](https://user-images.githubusercontent.com/78521567/108395435-c580ce80-71e3-11eb-8f00-17f2555d021a.PNG)

**Comment by kellypaulinc** [comment]
El monto recibido se inicializa con el total a cobrar que suma el detalle actual más el I.V.A menos el descuento.
