### ISSUE TITLE
Lista de pedidos debe cargar únicamente los pedidos del dia.

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#24]
![imagen](https://user-images.githubusercontent.com/1143320/108210196-3a2b0e80-70f9-11eb-9cde-6387595124da.png)

**Comment by kellypaulinc** [comment]
![solucion#24](https://user-images.githubusercontent.com/78521567/108429565-258c6a80-720e-11eb-8883-dc6ef9c85431.PNG)

**Comment by jlgranda** [comment]
Verificar si se afectaron las pantalla del menú "Iteligencia"

**Comment by kellypaulinc** [comment]
![solucion#24 3](https://user-images.githubusercontent.com/78521567/108529564-9715f880-72a2-11eb-982b-7938bd65d4c4.PNG)
![solucion#24 1](https://user-images.githubusercontent.com/78521567/108529569-98dfbc00-72a2-11eb-8b99-ed815969733a.PNG)
![solucion#24 2](https://user-images.githubusercontent.com/78521567/108529568-98472580-72a2-11eb-990b-35ce0964a14f.PNG)

**Comment by kellypaulinc** [comment]
No afecta las fechas, ni los datos de inteligencia
