### ISSUE TITLE
Pantalla de gráficos de productos no dibuja para el rango de fechas de 1 sólo día

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#28]
![Captura de pantalla de 2021-02-19 17-10-48](https://user-images.githubusercontent.com/1143320/108567151-acf0e100-72d5-11eb-98e5-39434f321e14.png)

**Comment by kellypaulinc** [comment]
![Uploading solucion#28.PNG…]()

**Comment by kellypaulinc** [comment]
![solucion#28](https://user-images.githubusercontent.com/78521567/108570851-d2351d80-72dc-11eb-9cfc-a5c713f83e26.PNG)
