### ISSUE TITLE
Agregar pantalla de gráfico de compras por proveedor.

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#29]
Agregar pantalla de gráfico de compras por proveedor en el menú "Inteligencia"

**Comment by kellypaulinc** [comment]
![solucion#29](https://user-images.githubusercontent.com/78521567/108749026-481fcb80-750d-11eb-947d-afa4c51f50a5.PNG)
Top de Proveedores por importe total de compras, en un rango de fechas establecido, (TOP 10).
