### ISSUE TITLE
Agregar campo categoría de productos. 

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#30]
Agregar campo categoría de productos: ventas y compras.

**Comment by kellypaulinc** [comment]
![solucion#30](https://user-images.githubusercontent.com/78521567/108910492-f1d98800-75f3-11eb-8e5f-547646a75e57.PNG)
![solucion#30 1](https://user-images.githubusercontent.com/78521567/108910505-f605a580-75f3-11eb-8717-984808cdc543.PNG)
Categorías de tipo PRODUCT.

**Comment by jlgranda** [comment]
En la lista de productos ampliar el filtro de fechas.
![Captura de pantalla de 2021-02-26 11-54-32](https://user-images.githubusercontent.com/1143320/109330302-87aa2880-7829-11eb-9bba-a616c9051bfe.png)

**Comment by kellypaulinc** [comment]
![solucion#30](https://user-images.githubusercontent.com/78521567/109558238-242d2e80-7aa7-11eb-8357-8249400b59b8.PNG)
