### ISSUE TITLE
Corregir cálculo de resumen en dashboard

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#36]
Al parecer esta tomando la fecha de creación del registro y no la fecha de emisión.

Agregar una línea TRANSFERENCIAS e indicar el total.

**Comment by kellypaulinc** [comment]
![solucion#36](https://user-images.githubusercontent.com/78521567/109838452-2cef4300-7c14-11eb-9563-1f492ae59c53.PNG)
Dashboard del mes de febrero

**Comment by kellypaulinc** [comment]
![solucion#36 1](https://user-images.githubusercontent.com/78521567/109851117-4b0f7000-7c21-11eb-9593-a2c52d6f6efb.PNG)
