### ISSUE TITLE
No guarda productos

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#40]
Al editar productos y seleccionar una categoría, no se guarda.
![imagen](https://user-images.githubusercontent.com/1143320/109974575-b6138200-7cc7-11eb-9056-a7badc81edc6.png)

**Comment by kellypaulinc** [comment]
https://user-images.githubusercontent.com/78521567/110163403-f9501c80-7dbd-11eb-853a-f1452a6cc599.mp4

**Comment by jlgranda** [comment]
Solucionado para ACTUALIZAR productos.
