### ISSUE TITLE
Agregar campo "pax" en Invoice.

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#41]
Agregar campo "pax" en Invoice.

**Comment by kellypaulinc** [comment]
![image](https://user-images.githubusercontent.com/78521567/110165809-7630c580-7dc1-11eb-98e5-103c1e0d923e.png)

**Comment by jlgranda** [comment]
¿Se agrego soporte en la vista?

**Comment by kellypaulinc** [comment]
![solucion#41 1](https://user-images.githubusercontent.com/78521567/110180077-23620880-7dd7-11eb-9459-a82355c1edb0.PNG)

**Comment by jlgranda** [comment]
Hacer un espacio a continuación de No de mesa
