### ISSUE TITLE
En listado de productos quitar filtros de fechas y agregar filtro de categorías

### ISSUE THREAD

**Issue by jlgranda** [jlgranda/appsventas#46]
Debería aparecer la lista completa de productos, y debe agregarse el filtro de categorías.

![Captura de pantalla de 2021-03-09 10-01-14](https://user-images.githubusercontent.com/1143320/110490743-9d87db00-80be-11eb-8954-203e682a99ad.png)

**Comment by kellypaulinc** [comment]
![solucion#46](https://user-images.githubusercontent.com/78521567/111002728-ea381400-8353-11eb-9058-40bd7644ea83.PNG)
